repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.3  # Use latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exists=true
          - --hook-config=--user-standard-markers=true
          - --hook-config=--custom-marker-begin=BEGIN_TF_DOCS
          - --hook-config=--custom-marker-end=END_TF_DOCS
          - --hook-config=--custom-doc-header=#
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_validate
      - id: terraform_tfsec
